<?php

namespace Core\AssetManager;

use Core\AssetManager\AssetConfig\AssetRegistrationConfig;
use Core\Exception\DuplicateEntryException;
use Core\Pathfinder;
use Core\Pathfinder\Path;
use InvalidArgumentException;
use Support\Time;
use Symfony\Component\VarExporter\Exception\ExceptionInterface;
use Symfony\Component\VarExporter\VarExporter;
use LogicException;

final readonly class AssetConfig
{
    protected Path $cachePath;

    public AssetRegistrationConfig $register;

    public Pathfinder $pathfinder;

    /** @var string[] */
    public array $assetDirectories;

    /**
     * @param string                $configCachePath
     * @param string                $projectAssetsDirectory
     * @param array<string, string> $additionalAssetDirectories
     */
    public function __construct(
        string $configCachePath,
        string $projectAssetsDirectory,
        array  $additionalAssetDirectories,
    ) {
        $parameters = $this->assetDirectories(
            $projectAssetsDirectory,
            $additionalAssetDirectories,
        );
        $this->pathfinder       = new Pathfinder( $parameters );
        $this->assetDirectories = \array_keys( $parameters );
        $this->cachePath        = new Path( $configCachePath );
        $this->register         = new AssetRegistrationConfig( $this );

        if ( $this->cachePath->getExtension() !== 'php' ) {
            $message = "The '".$this::class."->cachePath' must be a '.php' file.";
            throw new InvalidArgumentException( $message );
        }
    }

    public function createConfigCache() : void
    {
        try {
            $registeredAssets = VarExporter::export( $this->register->resolve() );
        }
        catch ( ExceptionInterface $e ) {
            throw new LogicException( $e->getMessage() );
        }

        $dateTime = Time::now();

        $name            = 'Registered Assets';
        $timestamp       = $dateTime->unixTimestamp;
        $date            = $dateTime->format( 'Y-m-d H:i:s e' );
        $generator       = __CLASS__;
        $contentDataHash = \hash( 'xxh3', $registeredAssets );

        $comment = 'Do not edit it manually.';

        $config = <<<PHP
            <?php
            
            /*--------------------------------------------------------{$timestamp}-
            
               Name      : {$name}
               Generated : {$date}
            
               This file is generated by:
               {$generator}.
            
               {$comment}
            
            -#{$contentDataHash}#------------------------------------------------*/
            
            return {$registeredAssets};
            PHP;

        $config = \rtrim( $config ).PHP_EOL;

        $config = (string) \preg_replace( '#^\h+$#m', '', $config );

        $content = \str_replace( PHP_EOL, "\n", $config );
        $this->cachePath->save( $content );
    }

    private function assetDirectories(
        string $projectAssetsDirectory,
        array  $additionalAssetDirectories,
    ) : array {
        $parameters = [
            'dir.assets' => $projectAssetsDirectory,
        ];

        foreach ( $additionalAssetDirectories as $key => $dir ) {
            if ( ! \is_string( $key ) || ! \str_starts_with( $key, 'dir.' ) ) {
                $message = $this::class." '\$assetDirectory' keys must be 'dir.parameter' keys.";
                throw new InvalidArgumentException( $message );
            }

            if ( \array_key_exists( $key, $parameters ) ) {
                throw new DuplicateEntryException( key : $key );
            }

            $parameters[$key] = Pathfinder::normalize( $dir );
        }

        return $parameters;
    }
}
