<?php

declare(strict_types=1);

namespace Core\AssetManager\Asset;

use Core\Asset\Type;
use JetBrains\PhpStorm\Deprecated;
use Stringable;
use InvalidArgumentException;
use function Support\{isPath, slug};

/**
 * Represents an asset reference with a specific name, type, source, and optional service pass.
 *
 * These are generated by {@see \Core\AssetManager\AssetConfig}
 * Used to build an asset and return its appropriate {@see \Core\AssetManager\Interface\AssetInterface}.
 *
 * @internal
 */
#[Deprecated]
final readonly class AssetReference implements Stringable
{
    /** @var string `type.name` */
    public string $name;

    public Type $type;

    /** @var string[] */
    public array $source;

    /** @var string[] */
    public array $servicePass;

    public AssetMeta $meta;

    /**
     * @param string               $name
     * @param string|string[]      $sources
     * @param string|string[]      $servicePass
     * @param array<string, mixed> $meta
     */
    public function __construct(
        string       $name,
        string|array $sources,
        string|array $servicePass = [],
        array        $meta = [],
    ) {
        \assert(
            \ctype_alnum( \str_replace( ['.', '-'], '', $name ) ),
            "Asset names must only contain ASCII letters, numbers, periods, and hyphens. '{$name}' provided.",
        );

        $this->name = $name;
        $this->type = Type::from( $name );

        // Set Sources
        $sources = (array) $sources;
        \ksort( $sources );
        $this->source = $sources;

        // Set Service calls
        $this->servicePass = (array) $servicePass;

        // Validate meta

        $this->meta = new AssetMeta( $meta );
    }

    public function __toString()
    {
        return $this->name;
    }

    public static function name( Stringable|string $from ) : string
    {
        if ( $from instanceof AssetReference ) {
            return $from->name;
        }

        if ( ! $name = (string) $from ) {
            throw new InvalidArgumentException( 'AssetReference name cannot be empty.' );
        }

        $type = \strtolower( Type::from( $name )->name );

        if ( \str_starts_with( $name, "{$type}." ) && \ctype_alnum( \str_replace( '.', '', $name ) ) ) {
            return $name;
        }

        if ( isPath( $name ) ) {
            $usePath = \strrchr( $name, '.', true ) ?: $name;

            $usePath = \str_replace( ['\\', '/'], '/', $usePath );

            $fromSource = "assets/{$type}";

            $strpos = \strpos( $usePath, $fromSource ) + \strlen( $fromSource );

            $trimmed = \substr( $usePath, $strpos );

            $name = \trim( \strstr( $trimmed, '/' ) ?: $trimmed, " \n\r\t\v\0/." );
        }

        \assert(
            \ctype_alnum( \str_replace( ['.', '-'], '', $name ) ),
            "AssetReference names must only contain ASCII letters, numbers, periods, and hyphens. '{$from}' provided.",
        );

        return "{$type}.".slug( $name );
    }

    private function validateMeta() : bool
    {
        foreach ( $this->meta as $key => $value ) {
            if ( ! \is_string( $key ) ) {
                return false;
            }
            \assert(
                \ctype_alnum( \str_replace( ['.', '-'], '', $key ) ),
                "AssetReference meta keys must only contain ASCII letters, numbers, periods, and hyphens. '{$key}' provided.",
            );
        }
        return true;
    }
}
